# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

variables:
- group: devopsforai-aml-vg

pool:
  vmImage: 'ubuntu-latest'
container: mcr.microsoft.com/mlops/python:latest

steps:

- task: CmdLine@2
  inputs:
    script: python $(Build.SourcesDirectory)/build_train_pipeline.py
  displayName: 'Run `build_train_pipeline.py'
